
---
title: "Analysis of posterior samples"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(ggplot2)
require(MCMCpack)
library(RColorBrewer)
```

* * *

```{r}
# Function to import data
source('../../utils/posterior_diag.R')
source("../../utils/load_data.R")
source('../../utils/metadata.R')
source('../../utils/calculate_disagreement_cohesion.R')
source('../../utils/view_results.R')
source('../../utils/compare_two_groups.R')
```

```{r}
datapath = '../../ANES_2016/anes_timeseries_2016/anes_timeseries_2016_rawdata.txt'
# Change this samplespath file
samplespath = '../simulation_results/fully_observed_withPI_13.RData'
load(samplespath)
n_cluster = 7 # Number of big clusters to be considered
```

```{r}
# posterior expectation of PI
expected_PI = matrix(rep(0,N*K),N,K)
for (i in 1:dim(PI)[1]) {
  PI_person = t(PI[i,,]) # 3000x30
  expected_PI[i,] = apply(PI_person, MARGIN = 2,mean)
}
```

```{r}
# number of associated profile
n_dominant_profile = apply(expected_PI > 0.1,MARGIN=1,sum)
barplot(table(n_dominant_profile)/sum(table(n_dominant_profile)), main = 'number of clusters with proportion > 10%')
table(n_dominant_profile)/sum(table(n_dominant_profile))
```

```{r}
# number of members
index_max = rep(0, N)
for (i in 1:N) {
  index_max[i] = which(expected_PI[i, ] == max(expected_PI[i, ]))
}
barplot(table(index_max)/sum(table(index_max)), main = 'number of main members')
table(index_max)/sum(table(index_max))
```


* * *



