
---
title: "Show results for 2 dem gorups in one realization"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(ggplot2)
require(MCMCpack)
library(xtable)
library(RColorBrewer)
```

* * *

```{r}
source("../../utils/load_data.R")
source('../../utils/metadata.R')
```

```{r}
# group 4 and 5 of seed 14 are dems
filepath_1 = '../simulation_results/fully_observed_14.RData'
group_a = 4
group_b = 5
# group 1 of seed 13 is dem
filepath_2 = '../simulation_results/fully_observed_13.RData'
group_base = 1
```


```{r, fig.width=5, fig.height=15}
# Part I: Load data
# Load results
load(filepath_1)
PHI_1 = PHI
BETA_1 = BETA
cluster_size_a = mean(BETA[, group_a])
cluster_size_b = mean(BETA[, group_b])
# Load results with missing data
load(filepath_2)
PHI_2 = PHI
BETA_2 = BETA
cluster_size_base = mean(BETA[, group_base])

# selected variables to be plotted
var_list = c(MAR_col, MCAR_col)
var_list = var_name
# Part II: Comparison of plots of pmf
par(mfrow=c(length(var_list),3), oma = c(1.5,4.5,1,0.2) + 0.1, mar = c(0.75,0.25,1.25,0.25) + 0.5)
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  
  # plot PHI for variable named var and for the selected group: group 1 of seed 13
  phi = t(PHI_2[[strtoi(idx)]][group_base,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
  
  # plot PHI for variable named var and for the selected group: group 4+5 of seed 14
  phi = t(PHI_1[[strtoi(idx)]][group_a,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7,
          yaxt = 'n')
  axis(side = 2, tick = TRUE, labels = FALSE)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
  
  # Add text for variable name
  mtext(text = var, side = 2, line = 1, cex = 0.5, las = 2, adj = 1.5, font = 2)
  
  phi = t(PHI_1[[strtoi(idx)]][group_b,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7,
          yaxt = 'n')
  axis(side = 2, tick = TRUE, labels = FALSE)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
}

# Part III: Summary table of pmfs
summary = c()
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  
  # Get posterior mean of the pmf of that variable: group 4+5 of seed 14
  phi = t(PHI_1[[strtoi(idx)]][group_a,,]) # matrix of size samples x # levels
  pmf_a =apply(phi, MARGIN=2, mean)
  
  phi = t(PHI_1[[strtoi(idx)]][group_b,,]) # matrix of size samples x # levels
  pmf_b =apply(phi, MARGIN=2, mean)
  
  
  # Get posterior mean of the pmf of that variable: group 1 of seed 13
  phi = t(PHI_2[[strtoi(idx)]][group_base,,]) # matrix of size samples x # levels
  pmf_base =apply(phi, MARGIN=2, mean)
  summary = rbind(summary, c(pmf_base, pmf_a, pmf_b))
}
colnames(summary) <- c('level = 1', 'level = 2', 'level = 3', 
                       'level = 1', 'level = 2', 'level = 3',
                       'level = 1', 'level = 2', 'level = 3')
rownames(summary) <- var_list
caption = paste("group base: ", group_base, " size = ", cluster_size_base,
                ", group a: ", group_a, " size = ", cluster_size_a, 
                ", group b: ", group_b, " size = ", cluster_size_b, sep = '')
xtable(summary, digits = 2, caption = caption)
```

```{r, fig.width=3, fig.height=15}
# Merge the two split group into one bigger group using BETA_1 and PHI_1

# create a weight matrix
w_a = BETA_1[,group_a]
w_b = BETA_1[,group_b]
w_a = matrix(rep(w_a,3), ncol = 3) # number of samples x number of levels
w_b = matrix(rep(w_b,3), ncol = 3) # number of samples x number of levels
w_total = w_a + w_b
print(apply(w_a, MARGIN = 2, mean))
print(apply(w_b, MARGIN = 2, mean))
print(apply(w_total, MARGIN = 2, mean))

# Part II: Comparison of plots of pmf
par(mfrow=c(length(var_list),2), oma = c(1.5,4.5,1,0.2) + 0.1, mar = c(0.75,0.25,1.25,0.25) + 0.5)
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  num_level= strtoi(meta[[var]][2])
  # plot PHI for variable named var and for the selected group: group 1 of seed 13
  phi = t(PHI_2[[strtoi(idx)]][group_base,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
  
  # Add text for variable name
  mtext(text = var, side = 2, line = 1, cex = 0.5, las = 2, adj = 1.5, font = 2)
  
  # plot PHI for variable named var and for the selected group: group 4+5 of seed 14
  phi_a = t(PHI_1[[strtoi(idx)]][group_a,,]) # matrix of size samples x # levels
  phi_a = phi_a*w_a
  phi_b = t(PHI_1[[strtoi(idx)]][group_b,,]) # matrix of size samples x # levels
  phi_b = phi_b*w_b
  phi = (phi_a + phi_b)/w_total
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7,
          yaxt = 'n')
  axis(side = 2, tick = TRUE, labels = FALSE)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
}

# Part III: Summary table of pmfs
summary = c()
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  
  # Get posterior mean of the pmf of that variable: group 4+5 of seed 14
  phi_a = t(PHI_1[[strtoi(idx)]][group_a,,]) # matrix of size samples x # levels
  phi_a = phi_a*w_a
  phi_b = t(PHI_1[[strtoi(idx)]][group_b,,]) # matrix of size samples x # levels
  phi_b = phi_b*w_b
  phi = (phi_a + phi_b)/w_total
  pmf_merge = apply(phi, MARGIN=2, mean)
  
  # Get posterior mean of the pmf of that variable: group 1 of seed 13
  phi = t(PHI_2[[strtoi(idx)]][group_base,,]) # matrix of size samples x # levels
  pmf_base =apply(phi, MARGIN=2, mean)
  summary = rbind(summary, c(pmf_base, pmf_merge))
}
colnames(summary) <- c('level = 1', 'level = 2', 'level = 3', 
                       'level = 1', 'level = 2', 'level = 3')
rownames(summary) <- var_list
caption = paste("group base: ", group_base, " size = ", cluster_size_base,
                ", group a+b, size = ", mean(w_total), sep = '')
xtable(summary, digits = 2, caption = caption)
```

* * *



