
---
title: "PMF of each ordinal variable"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(knitr)
library(dplyr)
library(arm)
library(pROC)
library(tidyverse)
library(MASS)
```

* * *
## Original version

```{r, echo = FALSE}
# here is the code to generate final dataset to be used in modelling
filepath = './anes_timeseries_2016/anes_timeseries_2016_rawdata.txt'
X = read.csv(filepath,sep= '|')
# select variables: 26 variables
var_name = c('V162123', 'V162134', 'V162140', 'V162145', 'V162146',
             'V162148', 'V162158', 'V162170', 'V162176', 'V162179',
             'V162180', 'V162192', 'V162193', 'V162207', 'V162208',
             'V162209', 'V162212', 'V162214', 'V162231', 'V162233', 
             'V162246', 'V162260', 'V162265', 'V162269', 'V162271', 
             'V162290')
X = X[, var_name]
# extract complete cases
complete_ind = (apply(X <= 0,MARGIN = 1, sum) == 0)
X = X[complete_ind,]
row.names(X) <- NULL
# fix problem with the lebel of V162290: levels 1,2,4,5 to 1,2,3,4
ind_4 = X[,'V162290']==4
X[ind_4,'V162290'] = 3
ind_5 = X[,'V162290']==5
X[ind_5,'V162290'] = 4
# Merge level 3 and 4 from V162192
ind_4 = X[,'V162192']==4
X[ind_4,'V162192'] = 3
# format data into categorical variables
level = apply(X, MARGIN=2, max)
X = data.frame(X)
for (col_index in 1:ncol(X)) {
  X[,col_index] = factor(X[,col_index], levels = 1:level[col_index])
}
X_original = X
N = dim(X)[1]
p = dim(X)[2]
```

```{r}
# ANES information for plotting

# variable names
var_name = c('V162123', 'V162134', 'V162140', 'V162145', 'V162146',
             'V162148', 'V162158', 'V162170', 'V162176', 'V162179',
             'V162180', 'V162192', 'V162193', 'V162207', 'V162208',
             'V162209', 'V162212', 'V162214', 'V162231', 'V162233', 
             'V162246', 'V162260', 'V162265', 'V162269', 'V162271', 
             'V162290')

# variable description
description = c('Agree/disagree: Better if rest of world more like America', 
                'How much opportunity is there in America today to get ahead?',
                'Favor or oppose tax on millionaires',
                'Health Care Law effect on cost of health care',
                'Favor or oppose vaccines in schools',
                'Favor or oppose government reducing income inequality',
                'How likely immigration will take away jobs',
                'Agree/disagree: Country needs strong leader to take us back to true path',
                'Favor or oppose free trade agreements with other countries',
                'Should marijuana be legal',
                'Should the government do more or less to regulate banks',
                'Should the minimum wage be raised',
                'Increase or decrease government spending to help people pay for health care',
                'Agree/disagree: world is changing and we should adjust',
                'Agree/disagree: newer lifestyles breaking down society',
                'Agree/disagree: We should be more tolerant of other moral standards',
                'Agree/disagree: past slavery and discrimination made it difficult for blacks to work their way out of the lower class',
                'Agree/disagree: if blacks would only try harder they could be just as well off as whites',
                'Should the news media pay more attention to discrimination against women?',
                'Do women complaining about discrimination cause more problems',
                'Agree/disagree: If people were treated more equally in this country we would have many fewer problems',
                'Agree/disagree: Most politicians do not care about the people',
                'Agree/disagree: Most politicians care only about the interests of the rich and powerful',
                'Agree/disagree: America’s culture is generally harmed by immigrants',
                'Agree/disagree: To be truly American important to have been born in U.S.',
                'Satisfied with way democracy works in the U.S.'
                )

# full level description for each variable
level_desc = c('1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=A great deal,
2= A lot,
3=A moderate amount,
4=A little,
5=None',
               '1=Favor,
2= Oppose,
3= Neither favor nor oppose',
               '1=Increased,
2= Decreased,
3= Had no effect',
               '1=Favor,
2= Oppose,
3= Neither favor nor oppose',
               '1=Favor,
2= Oppose,
3= Neither favor nor oppose',
               '1=Extremely likely,
2= Very likely,
3=Somewhat likely,
4=Not at all likely',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Favor,
2= Oppose,
3= Neither favor nor oppose',
               '1=Favor,
2= Oppose,
3= Neither favor nor oppose',
               '1=More,
2= Less,
3= The same',
               '1=Raised,
2= Kept the same,
3=Lowered or Eliminated',
               '1=Increase,
2= Decrease,
3= No change',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=More attention,
2= Less attention,
3=Same amount of attention',
               '1=Always,
2=Most of the time,
3=About half the time,
4=Some of the time,
5=Never',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Agree strongly,
2=Agree somewhat,
3=Neither agree nor disagree,
4=Disagree somewhat,
5=Disagree strongly',
               '1=Very important,
2=Fairly important,
3=Not very important,
4=Not important at all', 
               '1= Very satisfied,
2=Fairly satisfied,
3=Not very satisfied,
4=Not at all satisfied')

# Number of levels for each variable
level = apply(X_original, MARGIN=2, max)

# Combine everything into a metadata list for lookup
meta = list()
for (i in 1:p) {
  # description, number of levels, index
  meta[[var_name[i]]] = c(description[i], level[i], level_desc[i], i)
}
meta_original = meta
```

## Merged version

```{r}
# here is the code to generate final dataset to be used in modelling
filepath = './anes_timeseries_2016/anes_timeseries_2016_rawdata.txt'
X = read.csv(filepath,sep= '|')
# select variables: 26 variables
var_name = c('V162123', 'V162134', 'V162140', 'V162145', 'V162146',
             'V162148', 'V162158', 'V162170', 'V162176', 'V162179',
             'V162180', 'V162192', 'V162193', 'V162207', 'V162208',
             'V162209', 'V162212', 'V162214', 'V162231', 'V162233', 
             'V162246', 'V162260', 'V162265', 'V162269', 'V162271', 
             'V162290')
X = X[, var_name]
# extract complete cases
complete_ind = (apply(X <= 0,MARGIN = 1, sum) == 0)
X = X[complete_ind,]
row.names(X) <- NULL
# fix problem with the lebel of V162290: levels 1,2,4,5 to 1,2,3,4
ind_4 = X[,'V162290']==4
X[ind_4,'V162290'] = 3
ind_5 = X[,'V162290']==5
X[ind_5,'V162290'] = 4
# Merge level 3 and 4 from V162192
ind_4 = X[,'V162192']==4
X[ind_4,'V162192'] = 3
## Merge levels of response to simplify the model: old levels -> new level assignment
# V162123: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162123']==1) | (X[,'V162123']==2)
ind_2 = (X[,'V162123']==3)
ind_3 = (X[,'V162123']==4) | (X[,'V162123']==5)
X[ind_1,'V162123'] = 1
X[ind_2,'V162123'] = 2
X[ind_3,'V162123'] = 3
# V162134: 1+2->1, 3+4->2, 5->3
ind_1 = (X[,'V162134']==1) | (X[,'V162134']==2)
ind_2 = (X[,'V162134']==3) | (X[,'V162134']==4)
ind_3 = (X[,'V162134']==5)
X[ind_1,'V162134'] = 1
X[ind_2,'V162134'] = 2
X[ind_3,'V162134'] = 3
# V162140: no change
# V162145: no change
# V162146: no change
# V162148: no change
# V162158: 1->1, 2+3->2, 4->3
ind_1 = (X[,'V162158']==1)
ind_2 = (X[,'V162158']==2) | (X[,'V162158']==3)
ind_3 = (X[,'V162158']==4)
X[ind_1,'V162158'] = 1
X[ind_2,'V162158'] = 2
X[ind_3,'V162158'] = 3
# V162170: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162170']==1) | (X[,'V162170']==2)
ind_2 = (X[,'V162170']==3)
ind_3 = (X[,'V162170']==4) | (X[,'V162170']==5)
X[ind_1,'V162170'] = 1
X[ind_2,'V162170'] = 2
X[ind_3,'V162170'] = 3
# V162176: no change
# V162179: no change
# V162180: no change
# V162192: no change
# V162193: no change
# V162207: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162207']==1) | (X[,'V162207']==2)
ind_2 = (X[,'V162207']==3)
ind_3 = (X[,'V162207']==4) | (X[,'V162207']==5)
X[ind_1,'V162207'] = 1
X[ind_2,'V162207'] = 2
X[ind_3,'V162207'] = 3
# V162208: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162208']==1) | (X[,'V162208']==2)
ind_2 = (X[,'V162208']==3)
ind_3 = (X[,'V162208']==4) | (X[,'V162208']==5)
X[ind_1,'V162208'] = 1
X[ind_2,'V162208'] = 2
X[ind_3,'V162208'] = 3
# V162209: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162209']==1) | (X[,'V162209']==2)
ind_2 = (X[,'V162209']==3)
ind_3 = (X[,'V162209']==4) | (X[,'V162209']==5)
X[ind_1,'V162209'] = 1
X[ind_2,'V162209'] = 2
X[ind_3,'V162209'] = 3
# V162212: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162212']==1) | (X[,'V162212']==2)
ind_2 = (X[,'V162212']==3)
ind_3 = (X[,'V162212']==4) | (X[,'V162212']==5)
X[ind_1,'V162212'] = 1
X[ind_2,'V162212'] = 2
X[ind_3,'V162212'] = 3
# V162214: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162214']==1) | (X[,'V162214']==2)
ind_2 = (X[,'V162214']==3)
ind_3 = (X[,'V162214']==4) | (X[,'V162214']==5)
X[ind_1,'V162214'] = 1
X[ind_2,'V162214'] = 2
X[ind_3,'V162214'] = 3
# V162231: no change
# V162233: 1+2->1, 3+4->2, 5->3
ind_1 = (X[,'V162233']==1) | (X[,'V162233']==2)
ind_2 = (X[,'V162233']==3) | (X[,'V162233']==4)
ind_3 = (X[,'V162233']==5)
X[ind_1,'V162233'] = 1
X[ind_2,'V162233'] = 2
X[ind_3,'V162233'] = 3
# V162246: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162246']==1) | (X[,'V162246']==2)
ind_2 = (X[,'V162246']==3)
ind_3 = (X[,'V162246']==4) | (X[,'V162246']==5)
X[ind_1,'V162246'] = 1
X[ind_2,'V162246'] = 2
X[ind_3,'V162246'] = 3
# V162260: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162260']==1) | (X[,'V162260']==2)
ind_2 = (X[,'V162260']==3)
ind_3 = (X[,'V162260']==4) | (X[,'V162260']==5)
X[ind_1,'V162260'] = 1
X[ind_2,'V162260'] = 2
X[ind_3,'V162260'] = 3
# V162265: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162265']==1) | (X[,'V162265']==2)
ind_2 = (X[,'V162265']==3)
ind_3 = (X[,'V162265']==4) | (X[,'V162265']==5)
X[ind_1,'V162265'] = 1
X[ind_2,'V162265'] = 2
X[ind_3,'V162265'] = 3
# V162269: 1+2->1, 3->2, 4+5->3
ind_1 = (X[,'V162269']==1) | (X[,'V162269']==2)
ind_2 = (X[,'V162269']==3)
ind_3 = (X[,'V162269']==4) | (X[,'V162269']==5)
X[ind_1,'V162269'] = 1
X[ind_2,'V162269'] = 2
X[ind_3,'V162269'] = 3
# V162271: 1->1, 2+3->2, 4->3
ind_1 = (X[,'V162271']==1)
ind_2 = (X[,'V162271']==2) | (X[,'V162271']==3)
ind_3 = (X[,'V162271']==4)
X[ind_1,'V162271'] = 1
X[ind_2,'V162271'] = 2
X[ind_3,'V162271'] = 3
# V162290: 1->1, 2+3->2, 4->3
ind_1 = (X[,'V162290']==1)
ind_2 = (X[,'V162290']==2) | (X[,'V162290']==3)
ind_3 = (X[,'V162290']==4)
X[ind_1,'V162290'] = 1
X[ind_2,'V162290'] = 2
X[ind_3,'V162290'] = 3
# format data into categorical variables
level = apply(X, MARGIN=2, max)
X = data.frame(X)
for (col_index in 1:ncol(X)) {
  X[,col_index] = factor(X[,col_index], levels = 1:level[col_index])
}
X_merged = X
```

```{r}
# ANES information for plotting

# variable names
var_name = c('V162123', 'V162134', 'V162140', 'V162145', 'V162146',
             'V162148', 'V162158', 'V162170', 'V162176', 'V162179',
             'V162180', 'V162192', 'V162193', 'V162207', 'V162208',
             'V162209', 'V162212', 'V162214', 'V162231', 'V162233', 
             'V162246', 'V162260', 'V162265', 'V162269', 'V162271', 
             'V162290')

# variable description
description = c('Agree/disagree: Better if rest of world more like America', 
                'How much opportunity is there in America today to get ahead?',
                'Favor or oppose tax on millionaires',
                'Health Care Law effect on cost of health care',
                'Favor or oppose vaccines in schools',
                'Favor or oppose government reducing income inequality',
                'How likely immigration will take away jobs',
                'Agree/disagree: Country needs strong leader to take us back to true path',
                'Favor or oppose free trade agreements with other countries',
                'Should marijuana be legal',
                'Should the government do more or less to regulate banks',
                'Should the minimum wage be raised',
                'Increase or decrease government spending to help people pay for health care',
                'Agree/disagree: world is changing and we should adjust',
                'Agree/disagree: newer lifestyles breaking down society',
                'Agree/disagree: We should be more tolerant of other moral standards',
                'Agree/disagree: past slavery and discrimination made it difficult for blacks to work their way out of the lower class',
                'Agree/disagree: if blacks would only try harder they could be just as well off as whites',
                'Should the news media pay more attention to discrimination against women?',
                'Do women complaining about discrimination cause more problems',
                'Agree/disagree: If people were treated more equally in this country we would have many fewer problems',
                'Agree/disagree: Most politicians do not care about the people',
                'Agree/disagree: Most politicians care only about the interests of the rich and powerful',
                'Agree/disagree: America’s culture is generally harmed by immigrants',
                'Agree/disagree: To be truly American important to have been born in U.S.',
                'Satisfied with way democracy works in the U.S.'
                )

# full level description for each variable
level_desc = c('1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=A great deal/A lot,
2= A moderate amount/A little,
3=None',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Increased,
2= Decreased,
3= Had no effect',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Extremely likely,
2= Very likely/Somewhat likely,
3=Not at all likely',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=More,
2= Less,
3= The same',
'1=Raised,
2= Kept the same,
3=Lowered or Eliminated',
'1=Increase,
2= Decrease,
3= No change',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=More attention,
2= Less attention,
3=Same amount of attention',
'1=Always/Most of the time,
2=About half the time/Some of the time,
3=Never',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Very important,
2=Fairly important/Not very important,
3=Not important at all', 
'1= Very satisfied,
2=Fairly satisfied/Not very satisfied,
3=Not at all satisfied')

# Number of levels for each variable
level = apply(X_merged, MARGIN=2, max)

# Combine everything into a metadata list for lookup
meta = list()
for (i in 1:p) {
  # description, number of levels, index
  meta[[var_name[i]]] = c(description[i], level[i], level_desc[i], i)
}
meta_merged = meta
```

```{r, fig.height = 2, fig.width=4}
# histogram of each variable
par(cex.main = 0.75,cex.axis = 0.5)
n = dim(X_original)[1]
for (var in var_name) {
  # histogram of the original version
  summary_original = summary(X_original[,var])/n
  names(summary_original) = strsplit(meta_original[[var]][3], ",\n")[[1]]
  barplot(summary_original, xlab = 'level', ylab = 'pmf', 
          main = paste(var,': ', meta_original[[var]][1]), ylim = c(0,1),
          las = 1)
  # histogram of the merged version
  summary_merged = summary(X_merged[,var])/n
  names(summary_merged) = strsplit(meta_merged[[var]][3], ",\n")[[1]]
  barplot(summary_merged, xlab = 'level', ylab = 'pmf', 
          main = paste(var,': ', meta_merged[[var]][1]), ylim = c(0,1),
          las = 1)
}
```

* * *



