
---
title: "MMM model for fully observed dataset with bootstrapping"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(ggplot2)
require(MCMCpack)
library(RColorBrewer)
```

* * *

```{r}
# source our utility functions
source("../../utils/load_data.R")
source("../../utils/MMM_imputation.R")
```

```{r}
seed_number = 54
set.seed(seed_number)
# Import data
filepath = '../../ANES_2016/anes_timeseries_2016/anes_timeseries_2016_rawdata.txt'
X = load_data(filepath)
# Create a bootstrap dataset to represent X
row_ind = sample(nrow(X), size = nrow(X), replace = TRUE)
X_miss = X[row_ind,] # no missing values
row.names(X_miss) <- NULL
dim(X_miss)
length(table(row_ind)) # number of unique rows from original data matrix
min(row_ind)
max(row_ind)
```

```{r}
# Perform MMM modelling/imputation
savepath = paste('../simulation_results/fully_observed_bootstrap_', seed_number, '.RData', 
                 sep = '')
MMM_imputation(X_miss, K = 30, Mon = 30000, burnin = 15000, 
               thin = 5, seed = seed_number, 
               savename = savepath)
```
* * *



