
---
title: "View results from the modelling of ANES dataset with MMM"
output:
  pdf_document: default
  html_document:
    highlight: pygments
    theme: spacelab
---

```{r setup, echo =FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.pos = 'h', fig.align = 'center')
knitr::opts_chunk$set(fig.cap = "",  fig.path = "Plot")
library(ggplot2)
require(MCMCpack)
library(RColorBrewer)
```

* * *
```{r}
# Inputs
filepath_nonmissing = './samples_Sort_Beta/post_samples_mergedlv_sort_beta_long.RData'
filepath_missing = './samples_Sort_Beta/post_samples_mergedlv_sort_beta_long_MAR30.RData'
# groups to be plotted: 
# one group from nonmissing data (group_nonmissing), the other from missing data (group_missing)
group_nonmissing = 2
group_missing = 6
```

```{r}
# Load results with nonmissing data and prepare metadata
load(filepath_nonmissing)
# Number of observarions and covariates
N = dim(X)[1]
p = dim(X)[2]
K = ncol(BETA)
PHI_nonmissing = PHI

# Load results with missing data
load(filepath_missing)
PHI_missing = PHI

# constants
# variables subjected to MCAR
MCAR_col = c('V162123', 'V162148', 'V162170', 'V162192','V162209', 'V162246')
# variables subjected to MAR
MAR_col = c('V162140', 'V162158', 'V162179','V162207','V162214', 'V162269')
```

```{r}
# ANES information for plotting

# variable names
var_name = c('V162123', 'V162134', 'V162140', 'V162145', 'V162148', 'V162158', 
             'V162170', 'V162176', 'V162179', 'V162180', 'V162192', 'V162193', 
             'V162207', 'V162208', 'V162209', 'V162212', 'V162214', 'V162231', 
             'V162246', 'V162260', 'V162269', 'V162271', 'V162290')

# variable description
description = c('Agree/disagree: Better if rest of world more like America', 
                'How much opportunity is there in America today to get ahead?',
                'Favor or oppose tax on millionaires',
                'Health Care Law effect on cost of health care',
                'Favor or oppose government reducing income inequality',
                'How likely immigration will take away jobs',
                'Agree/disagree: Country needs strong leader to take us back to true path',
                'Favor or oppose free trade agreements with other countries',
                'Should marijuana be legal',
                'Should the government do more or less to regulate banks',
                'Should the minimum wage be raised',
                'Increase or decrease government spending to help people pay for health care',
                'Agree/disagree: world is changing and we should adjust',
                'Agree/disagree: newer lifestyles breaking down society',
                'Agree/disagree: We should be more tolerant of other moral standards',
                'Agree/disagree: past slavery and discrimination made it difficult for blacks to work their way out of the lower class',
                'Agree/disagree: if blacks would only try harder they could be just as well off as whites',
                'Should the news media pay more attention to discrimination against women?',
                'Agree/disagree: If people were treated more equally in this country we would have many fewer problems',
                'Agree/disagree: Most politicians do not care about the people',
                'Agree/disagree: America’s culture is generally harmed by immigrants',
                'Agree/disagree: To be truly American important to have been born in U.S.',
                'Satisfied with way democracy works in the U.S.'
                )

# full level description for each variable
level_desc = c('1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=A great deal/A lot,
2= A moderate amount/A little,
3=None',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Increased,
2= Decreased,
3= Had no effect',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Extremely likely,
2= Very likely/Somewhat likely,
3=Not at all likely',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=Favor,
2= Oppose,
3= Neither favor nor oppose',
'1=More,
2= Less,
3= The same',
'1=Raised,
2= Kept the same,
3=Lowered or Eliminated',
'1=Increase,
2= Decrease,
3= No change',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=More attention,
2= Less attention,
3=Same amount of attention',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Agree,
2=Neither agree nor disagree,
3=Disagree',
'1=Very important,
2=Fairly important/Not very important,
3=Not important at all', 
'1= Very satisfied,
2=Fairly satisfied/Not very satisfied,
3=Not at all satisfied')

# Number of levels for each variable
level = apply(X, MARGIN=2, max)

# Combine everything into a metadata list for lookup
meta = list()
for (i in 1:p) {
  # description, number of levels, index
  meta[[var_name[i]]] = c(description[i], level[i], level_desc[i], i)
}
```

### Customized plots for publications

```{r, fig.width=3, fig.height=9}
# plot selected variables for the selected group
var_list = c(MAR_col, MCAR_col)

# plotting section
par(mfrow=c(length(var_list),2), oma = c(1.5,4.5,1,0.2) + 0.1, mar = c(0.75,0.25,1.25,0.25) + 0.5)
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  
  # plot PHI for variable named var and for the selected group: nonmissing data
  phi = t(PHI_nonmissing[[strtoi(idx)]][group_nonmissing,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
  
  # Add text for variable name
  mtext(text = var, side = 2, line = 1, cex = 0.5, las = 2, adj = 1.5, font = 2)
  
  # plot PHI for variable named var and for the selected group: missing data
  phi = t(PHI_missing[[strtoi(idx)]][group_missing,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '',
          main = paste(var,': ', meta[[var]][1]), ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.7,
          yaxt = 'n')
  axis(side = 2, tick = TRUE, labels = FALSE)
  legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
}
```

```{r, fig.width=3, fig.height=6}
# plot selected variables for the selected group
var_list = c(MAR_col, MCAR_col)

# plotting section
par(mfrow=c(length(var_list),2), oma = c(1.5,4.5,1,0.2) + 0.1, mar = c(0.25,0.25,0.25,0.25)+0.25)
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  
  # plot PHI for variable named var and for the selected group: nonmissing data
  phi = t(PHI_nonmissing[[strtoi(idx)]][group_nonmissing,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '', ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.6,
          xaxt = 'n')
  #legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
  
  # Add text for variable name
  mtext(text = var, side = 2, line = 1, cex = 0.5, las = 2, adj = 1.5, font = 2)
  
  # plot PHI for variable named var and for the selected group: missing data
  phi = t(PHI_missing[[strtoi(idx)]][group_missing,,]) # matrix of size samples x # levels
  num_level= strtoi(meta[[var]][2])
  matplot(1:dim(phi)[1], phi, 
          type = 'l', ylab = 'phi', xlab = '', ylim = c(0,1),
          col=topo.colors(num_level), lwd = 1.5, cex.main = 0.7, cex.axis = 0.6,
          yaxt = 'n', xaxt = 'n')
  axis(side = 2, tick = TRUE, labels = FALSE)
  #legend('right', legend = 1:num_level, col=topo.colors(num_level), lwd = 1.5)
  legend('right', legend = c("choice 1", "choice 2", "choice 3"), 
       col=topo.colors(num_level), lwd = 1.5, cex = 0.7)
}

```

```{r, fig.width=3, fig.height=6}
# Table version
var_list = c(MAR_col, MCAR_col)
summary = c()
for (var in var_list) {
  idx = meta[[var]][4] # index for that variable
  
  # Get posterior mean of the pmf of that variable: without missing data
  phi = t(PHI_nonmissing[[strtoi(idx)]][group_nonmissing,,]) # matrix of size samples x # levels
  pmf_nonmissing =apply(phi, MARGIN=2, mean)

  
  # Get posterior mean of the pmf of that variable: with missing data
  phi = t(PHI_missing[[strtoi(idx)]][group_missing,,]) # matrix of size samples x # levels
  pmf_missing =apply(phi, MARGIN=2, mean)
  summary = rbind(summary, c(pmf_nonmissing, pmf_missing))
}
colnames(summary) <- c('level = 1', 'level = 2', 'level = 3', 
                       'level = 1', 'level = 2', 'level = 3')
rownames(summary) <- var_list
xtable(summary, digits = 2)
```

* * *



